name: 'Auto-Merge'

on:
  pull_request:
    types: [synchronize]

permissions:
    contents: read
    pull-requests: write

jobs:
  merge:
    name: 'Run'
    runs-on: ubuntu-latest

    steps:
    - name: 'Evaluate PR'
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: false
        labels: automated, merge
        checks_enabled: true
        method: squash
        delete_source_branch: true
