name: 'Quality Control'

on: 
  pull_request:
    types: [synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-suite:
    name: "Run Suite"
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Branch'
      uses: actions/checkout@v4

    - name: 'Initialize Environment'
      uses: ./.github/actions/initialize-environment

    - name: 'Safety Check Dependencies'
      run: |
        make safety_check

    - name: 'Lint Codebase'
      run: |
        make lint

    - name: 'Type Check Codebase'
      run: |
        make type_check

    - name: 'Validate Formatting'
      run: |
        make formatting

    - name: 'Run Tests'
      run: |
        make test

    - name: 'Generate Coverage Report'
      run: |
        make coverage_ci

    - name: 'Format Coverage Report'
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: success()
      with:
        filename: coverage.xml
        badge: false
        fail_below_min: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: 'Find PR Rumber'
      uses: jwalton/gh-find-current-pr@v1.3.2
      if: success()
      id: finder

    - name: 'Post Coverage Comment'
      uses: marocchino/sticky-pull-request-comment@v2.6.2
      if: success()
      with:
        number: ${{ steps.finder.outputs.pr }}
        recreate: true
        path: code-coverage-results.md
