name: 'Release Published'

on:
  pull_request:
    types: [synchronize]

permissions:
  contents: write

jobs:
  push-updated-changelog:
    name: "Update Changelog"
    runs-on: ubuntu-latest

    steps:
    - name: 'Generate Token'
      uses: actions/create-github-app-token@v1
      id: token-generator
      with:
        app-id: ${{ secrets.TOKEN_GENERATOR_APP_ID }}
        private-key: ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}

    - name: 'Checkout Branch'
      uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
        token: ${{ steps.token-generator.outputs.token }}

    - name: 'Initialize Environment'
      uses: ./.github/actions/initialize-environment

    - name: 'Generate Changelog'
      run: |
        make generate_changelog

    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
          target_branch: master
          commit_message: 'Update CHANGELOG !automated'
          access_token: ${{ steps.token-generator.outputs.token }}
